name=Tokyo Night
ghostty_theme=TokyoNight
wezterm_theme=TokyoNight
wallpaper=wallpaper/wallpaper.jpg
font=JetBrainsMono Nerd Font
font_size=11
border_radius=8
gaps_in=5
gaps_out=10
border_width=2
starship_directory=#7aa2f7
starship_git=#bb9af7
starship_success=#9ece6a
starship_error=#f7768e
