name=Catppuccin Mocha
ghostty_theme=Catppuccin Mocha
wezterm_theme=Catppuccin Mocha
wallpaper=wallpaper/wallpaper.jpg
font=JetBrainsMono Nerd Font
font_size=11
border_radius=12
gaps_in=5
gaps_out=12
border_width=2
starship_directory=#89b4fa
starship_git=#cba6f7
starship_success=#a6e3a1
starship_error=#f38ba8
