name=Gruvbox Dark
ghostty_theme=Gruvbox Dark
wezterm_theme=Gruvbox Dark
wallpaper=wallpaper/wallpaper.jpg
font=JetBrainsMono Nerd Font
font_size=11
border_radius=4
gaps_in=4
gaps_out=10
border_width=2
starship_directory=#83a598
starship_git=#d3869b
starship_success=#b8bb26
starship_error=#fb4934
