name=Rosé Pine
ghostty_theme=Rose Pine
wallpaper=wallpaper/wallpaper.jpg
font=JetBrainsMono Nerd Font
font_size=11
border_radius=10
gaps_in=5
gaps_out=12
border_width=2
starship_directory=#9ccfd8
starship_git=#c4a7e7
starship_success=#9ccfd8
starship_error=#eb6f92
