#!/usr/bin/env bash

RICE="$HOME/my-rice"

THEME=$(find "$RICE/themes" -mindepth 1 -maxdepth 1 -type d \
    -printf '%f\n' |
    sort |
    rofi -dmenu \
        -p "Theme" \
        -theme "$RICE/generated/current/theme.rasi")

[[ -z "$THEME" ]] && exit 0

"$RICE/scripts/theme-switcher" "$THEME"
